Repository DSM-PICK/PiCK_iOS_V2, pull requests merged in 2025-02, with the labels that each got.

#132 refact :: iPad 지원
  Projects/Modules/DesignSystem/Resources/Image.xcassets/Image/Contents.json
  Projects/Modules/DesignSystem/Resources/Image.xcassets/Image/mainBanner.imageset/Banner 2.png
  Projects/Modules/DesignSystem/Resources/Image.xcassets/Image/mainBanner.imageset/Banner.png
  Projects/Modules/DesignSystem/Resources/Image.xcassets/Image/mainBanner.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Image.xcassets/Image/noticeBanner.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Image.xcassets/Image/noticeBanner.imageset/blackNoticeBanner.png
  Projects/Modules/DesignSystem/Resources/Image.xcassets/Image/noticeBanner.imageset/noticeBanner.png
  Projects/Modules/DesignSystem/Resources/Image.xcassets/mainIcon/calendar.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Image.xcassets/mainIcon/calendar.imageset/Other 15.png
  Projects/Modules/DesignSystem/Sources/Extension/Image/UIImage+.swift
  Projects/Presentation/Sources/Scene/Home/HomeViewController.swift
  Projects/Presentation/Sources/Scene/Home/View/SelfStudyBannerView.swift
  Projects/Presentation/Sources/Scene/Login/LoginViewController.swift
Labels: REFACT

#134 fix :: [#133] 시간표 날짜 레이아웃 수정
  Projects/Presentation/Sources/Scene/Schedule/ScheduleViewController.swift
Labels: REFACT, FIX

#136 refact :: [#135] 일정 뷰 레이아웃 수정 및 코드 리펙토링
  Projects/Presentation/Sources/Scene/Schedule/ScheduleViewController.swift
  Projects/Presentation/Sources/Scene/Schedule/TimeTable/View/TimeTableView.swift
Labels: REFACT, CHORE

#138 refact :: 공지 등록 날짜 형식 변경
  Projects/Core/Sources/Util/UI/Calendar+.swift
  Projects/Core/Sources/Util/UI/Date+.swift
  Projects/Presentation/Sources/Scene/Notice/Cell/NoticeCollectionViewCell.swift
Labels: refact
