Repository DSM-PICK/PiCK_iOS_V2, pull requests merged in 2025-04, with the labels that each got.

#151 refact :: 자잘한 리펙
  Projects/Presentation/Sources/Scene/Notice/Cell/NoticeCollectionViewCell.swift
Labels: refact

#152 refact :: readme 수정
  README.md
Labels: refact

#154 feat :: 피커뷰의 값 변경을 감지 및 제한
  Projects/Modules/DesignSystem/Sources/Component/PickerView/PiCKOutingPickerContainerView.swift
  Projects/Modules/DesignSystem/Sources/Component/PickerView/PiCKPickerView.swift
Labels: feat

#153 refact :: 리드미 수정
  README.md
Labels: refact, chore

#156 feat :: [#118] SchoolMealView Calendar shadow 적용
  Projects/Modules/DesignSystem/Sources/Component/Calendar/PiCKCalendarView.swift
  Projects/Modules/DesignSystem/Sources/Component/PickerView/PiCKPickerView.swift
  Projects/Presentation/Sources/Scene/SchoolMeal/SchoolMealViewController.swift
Labels: feat

#160 refact :: [#59] tuist 마이그레이션
  .gitignore
  .mise.toml
  Makefile
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Projects/App/Project.swift
  Projects/Core/Project.swift
  Projects/Data/Project.swift
  Projects/Domain/Project.swift
  Projects/Flow/Project.swift
  Projects/Modules/AppNetwork/Project.swift
  Projects/Modules/DesignSystem/Project.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Projects/Presentation/Project.swift
  Projects/WatchModules/WatchAppNetwork/Project.swift
  Projects/WatchModules/WatchDesignSystem/Project.swift
  Projects/WatchModules/WatchThirdPartyLib/Project.swift
  Tuist/Dependencies.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/Project+Module.swift
Labels: refact

#161 fix :: [#158] 외출증 오류 해결
  Projects/Presentation/Sources/Scene/Home/HomeViewController.swift
  Projects/Presentation/Sources/Scene/Home/HomeViewModel.swift
Labels: fix

#163 feat :: [#162] 네트워크 모니터링 로직 추가
  Projects/Modules/DesignSystem/Sources/Component/Alert/PiCKAlert.swift
  Projects/Presentation/Sources/Base/BaseViewController.swift
  Projects/Presentation/Sources/Scene/OnBoarding/OnBoardingViewController.swift
Labels: feat

#165 feat :: [#131] 모니터링 시스템 구축
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/App/Project.swift
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Support/Info.plist
  Projects/Modules/ThirdPartyLib/Project.swift
  Tuist/Package.swift
Labels: feat

#168 feat :: [#166] 이미지 캐싱 처리
  Projects/App/WatchApp/Sources/Presentation/TimeTable/Cell/TimeTableCell.swift
  Projects/Modules/DesignSystem/Sources/Extension/UIImageView/UIImageView+Cache.swift
  Projects/Presentation/Sources/Scene/AllTab/MyPage/MyPageViewController.swift
  Projects/Presentation/Sources/Scene/Schedule/TimeTable/Cell/TimeTableCollectionViewCell.swift
Labels: feat
